SET SERVEROUTPUT ON;
CREATE OR REPLACE TYPE my_nested_table IS TABLE OF VARCHAR2(20);
/

CREATE TABLE my_sub(
        SUB_ID NUMBER,
        SUB_NAME VARCHAR2(20),
        SUB_SCH MY_NESTED_TABLE
        )
            NESTED TABLE SUB_SCH STORE AS NESTED_TAB;
        /
        
INSERT INTO MY_SUB(SUB_ID, SUB_NAME,SUB_SCH)
VALUES(101,'MATH',MY_NESTED_TABLE('MON','FRI'));

SELECT * FROM MY_SUB;