--------- PACKAGES_HEADER ------------

 CREATE OR REPLACE PACKAGE DEMO_PACKAGE IS 
    FUNCTION PRNT_STRNG RETURN VARCHAR2;
    PROCEDURE PRO_SUPERHERO (F_NAME VARCHAR2 , L_NAME VARCHAR2);
 END DEMO_PACKAGE;
 
 
 ---- PACKAGE BODY ----
 
 CREATE OR REPLACE PACKAGE BODY DEMO_PACKAGE IS
 
    -- FUNCTION IMPLEMENTATION
    FUNCTION PRNT_STRNG RETURN VARCHAR2 IS
        BEGIN
            RETURN 'hERE IS MY PACKAGE';
        END PRNT_STRNG;
        
     -- PROCEDURE IMPLEMENTATION
     PROCEDURE PRO_SUPERHERO(F_NAME VARCHAR2 , L_NAME VARCHAR2) IS 
        BEGIN
            INSERT INTO NEW_SUPERHERO(F_NAME , L_NAME)VALUES (F_NAME , L_NAME);
        END;
END DEMO_PACKAGE;
 
 
 ---CREATE TABLE NEW_SUPERHERO (F_NAME VARCHAR2(20) , L_NAME VARCHAR2(20));
 -- TO EXECUTE THE DATA
 SET SERVEROUTPUT ON;
 BEGIN
    DBMS_OUTPUT.PUT_LINE(DEMO_PACKAGE.PRNT_STRNG);
END;
/

----------------------------------------------
SELECT * FROM NEW_SUPERHERO;
BEGIN 
    DEMO_PACKAGE.PRO_SUPERHERO('TONY','STARK');
END;
/
 
 --------------------------------------------------------------------------------------------
 ----------------------------------- EXCEPTON HANDLING --------------------------------------
 DECLARE
    VAR_DIVIDEND NUMBER := 24;
    VAR_DIVISOR NUMBER := 8;
    VAR_RESULT NUMBER ;
    EX_DIVZERO EXCEPTION;
 BEGIN
   IF VAR_DIVISOR =0 THEN
        RAISE EX_DIVZERO;
    END IF;
    
    VAR_RESULT := VAR_DIVIDEND / VAR_DIVISOR;
    DBMS_OUTPUT.PUT_LINE('RESULT = '|| VAR_RESULT);
    
    EXCEPTION WHEN EX_DIVZERO THEN 
        DBMS_OUTPUT.PUT_LINE('ERRORRRR....!!!!!!!!');
    END;
    /
    
 
 ------------------------------
 -- USER DEFINED EXCEPTION USING RAOSE_APPLICATION_ERROR
 
 ACCEPT VAR_AGE NUMBER PROMPT ' wHAT IS YOUR AGE ??';
 DECLARE 
        AGE NUMBER := & VAR_AGE;
 BEGIN
        IF AGE < 18 THEN 
                RAISE_APPLICATION_ERROR(-2008, ' YOU SHOULD BE 18+ ');
        END IF;
        
        DBMS_OUTPUT.PUT_LINE('  sURE.. WHAT WOULD YU LIKE TO HAVE...');
        
        EXCEPTION WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE(SQLERRM);
    END;
    /
 
 ---------------
 --- PRAGMA EXCEPTION_INIT
 DECLARE
    DEADLOCK_DETECTED EXCEPTION;
    PRAGMA EXCEPTION_INIT(DEADLOCK_DETECTED, -60);
 BEGIN
    NULL;
 EXCEPTION
    WHEN DEADLOCK_DETECTED THEN NULL;
 END;
/